# Generated by Django 5.2.8 on 2025-12-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='pressure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
