# Generated by Django 5.2.8 on 2025-12-13 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0003_camera_photo_camera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='species',
        ),
        migrations.CreateModel(
            name='PhotoDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('count', models.PositiveIntegerField(default=1)),
                ('x', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('w', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('h', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('source', models.CharField(default='ai', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='wildlife.photo')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wildlife.species')),
            ],
        ),
    ]
