# Generated by Django 5.2.8 on 2025-12-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0004_remove_photo_species_photodetection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='environment',
        ),
        migrations.AddField(
            model_name='photo',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='time_taken',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
