# Generated by Django 5.2.8 on 2025-12-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0006_camera_opened_at_camera_opened_by_photo_opened_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photodetection',
            name='count',
        ),
        migrations.AddField(
            model_name='photodetection',
            name='category',
            field=models.CharField(blank=True, choices=[(1, 'Animal'), (2, 'Person'), (3, 'Vehicle')], help_text='Detection category (1=Animal, 2=Person, 3=Vehicle)', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='photodetection',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='photodetection',
            name='source',
            field=models.CharField(default='megadetector', max_length=50),
        ),
    ]
