# Generated by Django 5.2.8 on 2025-12-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0007_remove_photodetection_count_photodetection_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photodetection',
            name='species_confidence',
            field=models.FloatField(blank=True, help_text='Confidence for species_label', null=True),
        ),
        migrations.AddField(
            model_name='photodetection',
            name='species_label',
            field=models.CharField(blank=True, help_text='SpeciesNet predicted label', max_length=128, null=True),
        ),
    ]
