# Generated by Django 5.2.9 on 2025-12-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0009_rename_megadetector_result_photo_speciesnet_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photodetection',
            name='is_shown',
            field=models.BooleanField(default=True),
        ),
    ]
