# Generated by Django 5.2.9 on 2025-12-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0010_photodetection_is_shown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='base_latitude',
            field=models.DecimalField(decimal_places=17, max_digits=19),
        ),
        migrations.AlterField(
            model_name='camera',
            name='base_longitude',
            field=models.DecimalField(decimal_places=17, max_digits=19),
        ),
    ]
