# Generated by Django 6.0.4 on 2026-04-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0011_alter_camera_base_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
